#绑定端口
server:
  port: 9090
# mysql
spring:
  datasource:
    name: Qchat
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/Qchat?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 0
          min-idle: 0
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 0
          min-idle: 0
# jwt_token_过期时间
jwt:
  secret: sdsoaow28xasaslfcorfidufdidjfwfwsfsfdafafd
  access:
    expiration: 3600000    # 1 小时（毫秒）
  refresh:
    expiration: 86400000   # 24 小时（毫秒）
